Fix crash on Old GDB warning
On a system with gdb 7.6 and python 2.7, I get this nice traceback trying to install Gef:
```
Traceback (most recent call last):
  File "~/.gdbinit-gef.py", line 9473, in <module>
TypeError: sequence item 0: expected string, int found
```

Of course it's because `str.join('.', (7,7) )` doesn't work -- it needs the ints stringified. The fix is trivial, see diff.

In such a good project, having implemented the version check, you certainly don't want it to crash!